name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    name: Test Suite on ${{ matrix.os }} with rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
          - os: ubuntu-latest
            rust: nightly
          - os: macos-latest
            rust: stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y --no-install-recommends libgpg-error-dev

      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install gnupg

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --no-fail-fast

  docker-static:
    name: Build and test static (musl) configuration with docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build docker container
        run: docker build -f docker/Dockerfile.static -t test-build .

      - name: Run tests in container
        run: docker run test-build

  docker-windows:
    name: Build and test on windows with docker
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build docker container
        run: docker build --build-arg WIN_VARIANT=ltsc2019 -f docker/Dockerfile.windows -t test-build .

      - name: Run tests in container
        run: docker run test-build
